#pragma once

enum key_code
{
    DUMB_KEY_Q = 0,
    DUMB_KEY_W,
    DUMB_KEY_E,
    DUMB_KEY_R,
    DUMB_KEY_T,
    DUMB_KEY_Y,
    DUMB_KEY_U,
    DUMB_KEY_I,
    DUMB_KEY_O,
    DUMB_KEY_P,
    DUMB_KEY_A,
    DUMB_KEY_S,
    DUMB_KEY_D,
    DUMB_KEY_F,
    DUMB_KEY_G,
    DUMB_KEY_H,
    DUMB_KEY_J,
    DUMB_KEY_K,
    DUMB_KEY_L,
    DUMB_KEY_Z,
    DUMB_KEY_X,
    DUMB_KEY_C,
    DUMB_KEY_V,
    DUMB_KEY_B,
    DUMB_KEY_N,
    DUMB_KEY_M,
    DUMB_KEY_ESC,
    DUMB_KEY_ENTER,
    DUMB_KEY_1,
    DUMB_KEY_2,
    DUMB_KEY_3,
    DUMB_KEY_4,
    DUMB_KEY_5,
    DUMB_KEY_6,
    DUMB_KEY_7,
    DUMB_KEY_8,
    DUMB_KEY_9,
    
    DUMB_KEY_COUNT
};
